apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: spring-mysql-ecommerce-app
spec:
  selector:
    app: springboot-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080